# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "D:\\software\\.NET\\micro services\\EshopMicroservices\\src"
      dockerfile: "Services/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src\\Services\\Basket.API:/app:rw"
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src:/src:rw"
    - "C:\\Users\\Techno\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "D:\\software\\.NET\\micro services\\EshopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src:/src:rw"
    - "C:\\Users\\Techno\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "D:\\software\\.NET\\micro services\\EshopMicroservices\\src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discount.grpc:dev"
    ports: []
    volumes:
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src\\Services\\Discount\\\
      Discount.Grpc:/app:rw"
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src:/src:rw"
    - "C:\\Users\\Techno\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  ordering.api:
    build:
      context: "D:\\software\\.NET\\micro services\\EshopMicroservices\\src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Ordering.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ordering.api:dev"
    ports: []
    volumes:
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src\\Services\\Ordering\\\
      Ordering.API:/app:rw"
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src:/src:rw"
    - "C:\\Users\\Techno\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  yarpapigateway:
    build:
      context: "D:\\software\\.NET\\micro services\\EshopMicroservices\\src"
      dockerfile: "ApiGateways/YarpApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/YarpApiGateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "yarpapigateway:dev"
    ports: []
    volumes:
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src\\ApiGateways\\\
      YarpApiGateway:/app:rw"
    - "D:\\software\\.NET\\micro services\\EshopMicroservices\\src:/src:rw"
    - "C:\\Users\\Techno\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
