# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  catalog.api:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/Services/Catalog/Catalog.API:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
