# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "Services/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/Services/Basket.API:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/Services/Catalog/Catalog.API:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discount.grpc:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/Services/Discount/Discount.Grpc:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  ordering.api:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Ordering.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ordering.api:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/Services/Ordering/Ordering.API:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  shopping.web:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "WebApps/Shopping.Web/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Shopping.Web.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Shopping.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "shoppingweb:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/WebApps/Shopping.Web:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  yarpapigateway:
    build:
      context: "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src"
      dockerfile: "ApiGateways/YarpApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/YarpApiGateway.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "yarpapigateway:dev"
    ports: []
    volumes:
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src/ApiGateways/YarpApiGateway:/app:rw"
    - "/Users/irshadali/Desktop/code149/dotnet/microservices/EShopMicroservices/src:/src:rw"
    - "/Users/irshadali/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
