version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  redisinsight:
    image: redis/redisinsight:latest

  orderdb:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  messagebroker:
    image: rabbitmq:management
  
  catalog.api:
    #platform: linux/amd64
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    #platform: linux/amd64
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
  
  discount.grpc:
    #platform: linux/amd64
    image: ${DOCKER_REGISTRY-}discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  ordering.api:
    #platform: linux/amd64
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0

volumes:
  postgres_basket:
  postgres_catalog:
  redisinsight_data:
  elasticsearch-data: